// GENERATED by tool/extract_readme_snippets.dart from README.md — do not edit.
// Compile-only check that every README snippet uses the real API.
// ignore_for_file: unused_local_variable, unused_element, avoid_print, unused_import, unnecessary_await_in_return, dead_code, unused_catch_clause, prefer_const_constructors

import 'dart:async';

import 'package:firebase_auth_kit/firebase_auth_kit.dart';
import 'package:firebase_auth_kit/firebase_core.dart' as auth_core;
import 'package:test/test.dart' show test;

import 'helpers/readme_stubs.dart';

/// The README says every guide snippet assumes this line.
final auth = FirebaseAuth.instance;
// ---- README snippet 1 ----
Future<void> snippet1() async {
final auth = FirebaseAuth.instance;
await auth.createUserWithEmailAndPassword(email: 'ada@example.com', password: 'hunter22');
print('Hello ${auth.currentUser!.email}');

}

// ---- README snippet 2 ----

Future<void> main2() async {
  final auth = FirebaseAuth.instance;   // finds your Firebase config automatically

  // Tell the UI whenever the user signs in or out.
  auth.authStateChanges().listen((User? user) {
    print(user == null ? 'signed out' : 'signed in as ${user.email}');
  });

  try {
    await auth.createUserWithEmailAndPassword(
      email: 'ada@example.com',
      password: 'correct horse battery staple',
    );
  } on FirebaseAuthException catch (e) {
    print(e.userMessage);   // e.g. "An account already exists with that email address."
  }

  final idToken = await auth.currentUser?.getIdToken();
  print('send this to your backend: $idToken');
}


// ---- README snippet 3 ----

void main3() async {
  DartNativePluginRegistrant.registerAll();
  await installSecureAuthPersistence(SecureStorage());   // restores last session too
  runApp(const MyApp());
}


// ---- README snippet 4 ----

Future<void> main4() async {
  await auth_core.Firebase.initializeApp(
    options: const auth_core.FirebaseOptions(
      apiKey: 'AIzaSy...',
      appId: '1:123456789:web:abc123',
      messagingSenderId: '123456789',
      projectId: 'my-project',
    ),
  );
  final credential = await FirebaseAuth.instance.signInWithEmailAndPassword(
    email: 'ada@example.com',
    password: 'correct horse battery staple',
  );
  print(credential.user!.uid);
}


// ---- README snippet 5 ----
Future<void> snippet5() async {
final auth = FirebaseAuth.instance;

}

// ---- README snippet 6 ----
Future<void> snippet6() async {
// Sign up (creates the account and signs in)
final signUp = await auth.createUserWithEmailAndPassword(
  email: email,
  password: password,
);
print('new uid: ${signUp.user!.uid}');

// Sign in
await auth.signInWithEmailAndPassword(email: email, password: password);

// Who is signed in?
final user = auth.currentUser;
print('${user?.email} verified=${user?.emailVerified}');

// Sign out
await auth.signOut();

}

// ---- README snippet 7 ----
Future<void> snippet7() async {
await auth.currentUser!.sendEmailVerification();
// Later, after they clicked the link in the mail:
await auth.currentUser!.reload();
print(auth.currentUser!.emailVerified);   // true

}

// ---- README snippet 8 ----
Future<void> snippet8() async {
await auth.sendPasswordResetEmail(email: email);
// Firebase emails a link. With the default Firebase-hosted page the user sets a new password
// there and nothing else is needed. If you host your own page, finish it with:
await auth.confirmPasswordReset(code: oobCodeFromLink, newPassword: newPassword);

}

// ---- README snippet 9 ----
Future<void> snippet9() async {
await auth.currentUser!.updatePassword(newPassword);

}

// ---- README snippet 10 ----
Future<void> snippet10() async {
try {
  await auth.currentUser!.updatePassword(newPassword);
} on FirebaseAuthException catch (e) {
  if (e.requiresRecentLogin) {
    await auth.currentUser!.reauthenticateWithCredential(
      EmailAuthProvider.credential(email: email, password: currentPassword),
    );
    await auth.currentUser!.updatePassword(newPassword);
  }
}

}

// ---- README snippet 11 ----
Future<void> snippet11() async {
await auth.setLanguageCode('fr');

}

// ---- README snippet 12 ----

void main12() async {
  DartNativePluginRegistrant.registerAll();
  await installSecureAuthPersistence(SecureStorage());
  runApp(const MyApp());
}


// ---- README snippet 13 ----
class MyStore extends AuthPersistence {
  @override
  Future<String?> read(String key) async => /* fetch */ null;
  @override
  Future<void> write(String key, String value) async {/* save */}
  @override
  Future<void> delete(String key) async {/* remove */}
}

void main13() async {
  FirebaseAuthKit.persistence = MyStore();
  await FirebaseAuth.instance.authStateReady();   // wait for the async store
  runApp(const MyApp());
}


// ---- README snippet 14 ----
Future<void> snippet14() async {
await auth.setPersistence(Persistence.NONE);   // memory only, gone when the app exits

}

// ---- README snippet 15 ----
Future<void> snippet15() async {
auth.authStateChanges().listen((User? user) {
  if (user == null) {
    router.go('/login');
  } else {
    router.go('/home');
  }
});

}

// ---- README snippet 16 ----
Future<void> snippet16() async {
auth.userChanges().listen((user) => nameLabel.text = user?.displayName ?? '');

}

// ---- README snippet 17 ----
Future<void> snippet17() async {
await FirebaseAuth.instance.authStateReady();
runApp(MyApp(startSignedIn: FirebaseAuth.instance.currentUser != null));

}

// ---- README snippet 18 ----
Future<void> snippet18() async {
await auth.signInAnonymously();
print(auth.currentUser!.isAnonymous);   // true

// Later: upgrade in place, same uid
await auth.currentUser!.linkWithCredential(
  EmailAuthProvider.credential(email: email, password: password),
);
print(auth.currentUser!.isAnonymous);   // false

}

// ---- README snippet 19 ----
Future<void> snippet19() async {
final account = await GoogleSignIn(serverClientId: 'YOUR-WEB-CLIENT-ID').signIn();
if (account != null) {
  final googleAuth = account.authentication;
  final result = await auth.signInWithCredential(
    GoogleAuthProvider.credential(
      idToken: googleAuth.idToken,
      accessToken: googleAuth.accessToken,
    ),
  );
  print('${result.user!.displayName}, new: ${result.additionalUserInfo!.isNewUser}');
}

}

// ---- README snippet 20 ----
Future<void> snippet20() async {
final rawNonce = generateRandomNonce();               // any 32+ random characters
final appleCredential = await SignInWithApple.getAppleIDCredential(
  scopes: [AppleIDAuthorizationScopes.email, AppleIDAuthorizationScopes.fullName],
  nonce: sha256Hex(rawNonce),                         // Apple gets the hash…
);
await auth.signInWithCredential(
  AppleAuthProvider.credentialWithIDToken(
    appleCredential.identityToken!,
    rawNonce,                                         // …Firebase gets the raw value
    AppleFullPersonName(
      givenName: appleCredential.givenName,
      familyName: appleCredential.familyName,
    ),
  ),
);

}

// ---- README snippet 21 ----
Future<void> snippet21() async {
await auth.signInWithCredential(FacebookAuthProvider.credential(facebookAccessToken));
await auth.signInWithCredential(GithubAuthProvider.credential(githubAccessToken));
await auth.signInWithCredential(
  OAuthProvider('microsoft.com').credential(idToken: msIdToken, accessToken: msAccessToken),
);

}

// ---- README snippet 22 ----
Future<void> snippet22() async {
await auth.currentUser!.linkWithCredential(GoogleAuthProvider.credential(idToken: idToken));
print(auth.currentUser!.providerData.map((p) => p.providerId));  // (password, google.com)
await auth.currentUser!.unlink('google.com');

}

// ---- README snippet 23 ----
Future<void> snippet23() async {
try {
  await auth.signInWithCredential(googleCredential);
} on FirebaseAuthException catch (e) {
  if (e.errorCode == FirebaseAuthErrorCode.accountExistsWithDifferentCredential) {
    // 1. sign in with the method the account already has (e.email tells you which user)
    await auth.signInWithEmailAndPassword(email: e.email!, password: passwordFromUser);
    // 2. attach Google to it so both work from now on
    await auth.currentUser!.linkWithCredential(e.credential!);
  }
}

}

// ---- README snippet 24 ----
Future<void> snippet24() async {
final result = await auth.signInWithProvider(
  GithubAuthProvider()..addScope('user:email'),
);
await auth.currentUser!.linkWithProvider(MicrosoftAuthProvider());
await auth.currentUser!.reauthenticateWithProvider(GithubAuthProvider());

}

// ---- README snippet 25 ----
Future<void> snippet25() async {
String? verificationId;

await auth.verifyPhoneNumber(
  phoneNumber: '+15555550123',                       // E.164: plus sign and country code
  codeSent: (id, resendToken) {
    verificationId = id;
    showCodeEntryScreen();
  },
  verificationCompleted: (credential) => auth.signInWithCredential(credential),
  verificationFailed: (e) => showError(e.userMessage),
  codeAutoRetrievalTimeout: (id) {},
);

// after the user typed the 6 digits:
await auth.signInWithCredential(
  PhoneAuthProvider.credential(verificationId: verificationId!, smsCode: smsCode),
);

}

// ---- README snippet 26 ----
Future<void> snippet26() async {
final confirmation = await auth.signInWithPhoneNumber('+15555550123');
await confirmation.confirm(smsCode);

}

// ---- README snippet 27 ----
Future<void> snippet27() async {
// 1. send the link
await auth.sendSignInLinkToEmail(
  email: email,
  actionCodeSettings: ActionCodeSettings(
    url: 'https://myapp.example.com/finish-sign-in',   // where the link lands
    handleCodeInApp: true,                             // required for email links
    iOSBundleId: 'com.example.myapp',
    androidPackageName: 'com.example.myapp',
    androidInstallApp: true,
  ),
);
saveLocally(email);   // you need it again in step 2

// 2. when the app is opened from the link (app_links_kit gives you the URL):
if (auth.isSignInWithEmailLink(link)) {
  await auth.signInWithEmailLink(email: savedEmail, emailLink: link);
}

}

// ---- README snippet 28 ----
Future<void> snippet28() async {
final user = auth.currentUser!;
final session = await user.multiFactor.getSession();
final secret = await TotpMultiFactorGenerator.generateSecret(session);

// Show this as a QR code, or let them copy secret.secretKey
final qrUrl = await secret.generateQrCodeUrl(accountName: user.email, issuer: 'My App');

// The user types the 6-digit code from the authenticator app:
final assertion = await TotpMultiFactorGenerator.getAssertionForEnrollment(secret, codeFromApp);
await user.multiFactor.enroll(assertion, displayName: 'Authenticator app');

}

// ---- README snippet 29 ----
Future<void> snippet29() async {
final session = await auth.currentUser!.multiFactor.getSession();
String? enrolmentVerificationId;
await auth.verifyPhoneNumber(
  phoneNumber: '+15555550123',
  multiFactorSession: session,
  codeSent: (id, _) => enrolmentVerificationId = id,
  verificationCompleted: (_) {},
  verificationFailed: (e) => showError(e.userMessage),
  codeAutoRetrievalTimeout: (_) {},
);
// after the SMS code arrives:
await auth.currentUser!.multiFactor.enroll(
  PhoneMultiFactorGenerator.getAssertion(
    PhoneAuthProvider.credential(verificationId: enrolmentVerificationId!, smsCode: smsCode),
  ),
  displayName: 'My phone',
);

}

// ---- README snippet 30 ----
Future<void> snippet30() async {
try {
  await auth.signInWithEmailAndPassword(email: email, password: password);
} on FirebaseAuthMultiFactorException catch (e) {
  final resolver = e.resolver;
  final hint = resolver.hints.first;                 // the factors the user enrolled

  if (hint is TotpMultiFactorInfo) {
    final assertion = await TotpMultiFactorGenerator.getAssertionForSignIn(hint.uid, codeFromApp);
    await resolver.resolveSignIn(assertion);
  } else if (hint is PhoneMultiFactorInfo) {
    String? verificationId;
    await auth.verifyPhoneNumber(
      multiFactorInfo: hint,
      multiFactorSession: resolver.session,
      codeSent: (id, _) => verificationId = id,
      verificationCompleted: (_) {},
      verificationFailed: (e) => showError(e.userMessage),
      codeAutoRetrievalTimeout: (_) {},
    );
    // after the SMS code arrives:
    await resolver.resolveSignIn(
      PhoneMultiFactorGenerator.getAssertion(
        PhoneAuthProvider.credential(verificationId: verificationId!, smsCode: smsCode),
      ),
    );
  }
}

}

// ---- README snippet 31 ----
Future<void> snippet31() async {
final token = await auth.currentUser!.getIdToken();
final response = await http.get(
  Uri.parse('https://api.example.com/me'),
  headers: {'Authorization': 'Bearer $token'},
);

}

// ---- README snippet 32 ----
Future<void> snippet32() async {
final result = await auth.currentUser!.getIdTokenResult();
print(result.claims?['admin']);          // custom claims set by your backend
print(result.signInProvider);            // 'password', 'google.com', 'phone', …
print(result.expirationTime);

}

// ---- README snippet 33 ----
Future<void> snippet33() async {
FirebaseFirestore.instance.tokenProvider =
    () async => await FirebaseAuth.instance.currentUser?.getIdToken();

}

// ---- README snippet 34 ----
Future<void> snippet34() async {
final user = auth.currentUser!;

await user.updateProfile(displayName: 'Ada Lovelace', photoURL: 'https://…/ada.png');
await user.updateDisplayName(null);            // remove it
await user.verifyBeforeUpdateEmail('new@example.com');   // emails a confirmation link first
await user.updatePassword(newPassword);
await user.reload();                            // pull the latest server state
await user.delete();                            // signs out too

}

// ---- README snippet 35 ----
Future<void> snippet35() async {
try {
  await auth.signInWithEmailAndPassword(email: email, password: password);
} on FirebaseAuthMultiFactorException catch (e) {
  startSecondFactor(e.resolver);
} on FirebaseAuthException catch (e) {
  if (e.isInvalidCredentials) {
    showFieldError(e.userMessage);      // wrong email/password, whichever code the project returns
  } else if (e.isRetryable) {
    showRetry(e.userMessage);           // offline, timeout, rate limited
  } else if (e.requiresRecentLogin) {
    askToSignInAgain();
  } else if (e.isDeveloperError) {
    log('Auth misconfigured: ${e.code} ${e.message}');   // e.g. provider not enabled
    showError(e.userMessage);
  } else {
    showError(e.userMessage);
  }
}

}

// ---- README snippet 36 ----
Future<void> snippet36() async {
FirebaseAuthKit.errorMessages = {
  FirebaseAuthErrorCode.invalidCredential: 'E-mail ou mot de passe incorrect.',
  FirebaseAuthErrorCode.networkRequestFailed: 'Pas de connexion internet.',
};

}

// ---- README snippet 37 ----
Future<void> snippet37() async {
try {
} catch (error) {
  showError(FirebaseAuthKit.describeError(error));
}

}

// ---- README snippet 38 ----
Future<void> snippet38() async {
final result = await auth.signInWithCustomToken(tokenFromYourServer);
print(result.user!.uid);   // the uid your server put in the token
final claims = (await result.user!.getIdTokenResult()).claims;   // your custom claims

}

// ---- README snippet 39 ----
Future<void> snippet39() async {
final staging = await auth_core.Firebase.initializeApp(
  name: 'staging',
  options: const auth_core.FirebaseOptions(
    apiKey: 'AIza…', appId: '1:…', messagingSenderId: '…', projectId: 'my-staging',
  ),
);
final stagingAuth = FirebaseAuth.instanceFor(app: staging);

}

// ---- README snippet 40 ----
Future<void> snippet40() async {
await auth.useAuthEmulator('localhost', 9099);   // 'localhost' becomes 10.0.2.2 on Android emulators

}

// ---- README snippet 41 ----
Future<void> snippet41() async {
FirebaseAuthKit.logger = print;
// [firebase_auth_kit] POST /v1/accounts:signInWithPassword 200
// [firebase_auth_kit] POST /v1/securetoken.googleapis.com/v1/token 200

}

// ---- README snippet 42 ----
Future<void> snippet42() async {
setUp(() {
  FirebaseAuthKit.reset();
  FirebaseAuthKit.persistence = InMemoryAuthPersistence();
  FirebaseAuthKit.emulatorHost = 'http://127.0.0.1:9099';   // or your fake server's origin
});

}

// ---- README snippet 43 ----

/// Shows a Firebase auth page and completes with the redirect the kit expects.
class AuthWebPage extends StatefulWidget {
  const AuthWebPage({super.key, required this.url, required this.isCallback});
  final Uri url;
  final bool Function(Uri) isCallback;

  @override
  State<AuthWebPage> createState() => _AuthWebPageState();
}

class _AuthWebPageState extends State<AuthWebPage> {
  final controller = WebViewController();
  bool done = false;

  @override
  void initState() {
    super.initState();
    controller.setJavaScriptMode(JavaScriptMode.unrestricted);
    controller.setNavigationDelegate(NavigationDelegate(
      onNavigationRequest: (request) {
        if (_finish(request.url)) return NavigationDecision.prevent;
        return NavigationDecision.navigate;
      },
      // The redirect normally arrives above (dartnative_webview 1.0.1+); page
      // loads are checked too, so the screen also works with web views that
      // only report those.
      onPageStarted: _finish,
      onPageFinished: _finish,
    ));
    controller.loadRequest(widget.url);
  }

  bool _finish(String url) {
    final target = Uri.tryParse(url);
    if (target != null && widget.isCallback(target) && !done) {
      done = true;
      Navigator.of(context).pop(target);           // hand the result back
      return true;
    }
    return false;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Sign in')),
      body: WebViewWidget(controller: controller),
    );
  }
}

/// Register it once, where you have a navigator (a global key works too).
void installAuthWebFlow(BuildContext context) {
  FirebaseAuthKit.webFlowPresenter = (url, {required isCallback}) {
    return Navigator.of(context).push<Uri?>(
      PageRoute(builder: (_) => AuthWebPage(url: url, isCallback: isCallback)),
    );
  };
}


// ---- README snippet 44 ----

void main44() async {
  DartNativePluginRegistrant.registerAll();
  await DnFirebase.initializeApp();        // dartnative_firebase (native SDKs)
  final auth = FirebaseAuth.instance;    // firebase_auth_kit — same project, discovered
  runApp(const MyApp());
}


void main() {
  test('README snippets compile', () {});
}
