// Extracts every ```dart block from README.md into
// test/readme_snippets_test.dart so `dart analyze` proves the documentation
// compiles against the current API. Run: dart run tool/extract_readme_snippets.dart
import 'dart:io';

const _prelude = r'''
// GENERATED by tool/extract_readme_snippets.dart from README.md — do not edit.
// Compile-only check that every README snippet uses the real API.
// ignore_for_file: unused_local_variable, unused_element, avoid_print, unused_import, unnecessary_await_in_return, dead_code, unused_catch_clause, prefer_const_constructors

import 'dart:async';

import 'package:firebase_auth_kit/firebase_auth_kit.dart';
import 'package:firebase_auth_kit/firebase_core.dart' as auth_core;
import 'package:test/test.dart' show test;

import 'helpers/readme_stubs.dart';

/// The README says every guide snippet assumes this line.
final auth = FirebaseAuth.instance;
''';

void main() {
  final readme = File('README.md').readAsStringSync();
  final blocks = RegExp(r'```dart\n(.*?)```', dotAll: true)
      .allMatches(readme)
      .map((m) => m.group(1)!)
      .toList();

  final out = StringBuffer(_prelude);
  var index = 0;
  for (var block in blocks) {
    index++;
    // Drop imports the stubs replace; keep firebase_auth_kit ones out too
    // (already imported above) so the file has a single import section.
    final lines = block.split('\n');
    final body = lines.where((l) => !l.trimLeft().startsWith('import ')).join('\n');
    final usesPrefixedCore = block.contains("firebase_core.dart' as auth_core");
    final usesCore = block.contains('firebase_core.dart');
    var code = body;
    if (usesPrefixedCore) {
      // Already prefixed in the README.
    } else if (usesCore) {
      code = code
          .replaceAll(RegExp(r'\bFirebase\.'), 'auth_core.Firebase.')
          .replaceAll(RegExp(r'\bFirebaseOptions\('), 'auth_core.FirebaseOptions(');
    } else if (block.contains('dartnative_firebase')) {
      code = code.replaceAll(RegExp(r'\bFirebase\.'), 'DnFirebase.');
    }
    final isTopLevel = RegExp(r'^(Future<void> |void )?main\(|^class ', multiLine: true)
        .hasMatch(code);
    out.writeln('// ---- README snippet $index ----');
    if (isTopLevel) {
      code = code.replaceAll(RegExp(r'\bmain\('), 'main$index(');
      out.writeln(code);
    } else {
      var fragment = code.trimLeft();
      if (fragment.startsWith('}')) fragment = 'try {\n$fragment';
      out.writeln('Future<void> snippet$index() async {');
      out.writeln(fragment);
      out.writeln('}');
    }
    out.writeln();
  }
  out.writeln("void main() {\n  test('README snippets compile', () {});\n}");
  File('test/readme_snippets_test.dart').writeAsStringSync(out.toString());
  stdout.writeln('wrote ${blocks.length} snippets');
}
